### ISSUE TITLE
Problem with weather.com (mparticle.com) - solved by old.reddit.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1034]
@Rusenche commented on [Fri Sep 02 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/370)

https://old.reddit.com/r/uBlockOrigin/comments/x3fskl/problem_with_weathercom/ - open this address, read the reviews and be sure of the decision.

https://old.reddit.com/r/uBlockOrigin/comments/x3fskl/problem_with_weathercom/imte4mf/

> After many tests it turned out that...

> The problem for me was that in the settings of Chromium v.105.0.5195.54 in Settings -> Privacy and security -> Security -> Use secure DNS -> Custom -> **https://dns.adguard.com/dns-query** or **https://dns-family.adguard.com/dns-query**.
> 
> Adding either DNS-over-HTTPS:
> 1. **https://dns.adguard.com/dns-query**;
> 2. **https://dns-family.adguard.com/dns-query**

1. https://i.postimg.cc/j2m1NjMX/1.png
2. https://i.postimg.cc/DfMHRC7X/2.png

> **was causing the _weather.com_ search bar to be unable to type/use.**
> 
> Hope this helps someone, because I was surprised that the problem was caused by adding Adguard DNS-over-HTTPS to the browser.

**I hope you will take a stand on this particular issue in this thread so we can get back to using your Adguard DNS-over-HTTPS to the browser.**

**Comment by Alex-302** [comment]
Cannot reproduce

<details>
<summary>Details</summary>


![image](https://user-images.githubusercontent.com/8361299/188235478-03dacd46-a4e8-41c5-9e6f-1bb251cf1fdf.png)

</details>

**Comment by Rusenche** [comment]
How can you not reproduce it?! Did you put the addresses as in the pictures?! Obviously the problem is with the DNS addresses! I found it experimentally!

Tested with:
1. Thorium v.107.0.5271.0;
2. Ungoogled Chromium v.105.0.5195.54;
3. LibreWolf v.104.0;
4. Mozilla Firefox v.104.0.1.

Removed my modified hosts file.

Tested everywhere in all browsers with clean profiles without any extensions!

Only after pasting https://dns.adguard.com/dns-query or https://dns-family.adguard.com/dns-query and the search field is inactive, it cannot be written to.

Restart your browser when testing to pick up the changes when pasting and testing these two addresses. Otherwise, it will always show you that the problem is somewhere else...

So I reproduced it and proved it! As long as you won't change anything and locked the topic, => I'm done using both DNS-over-HTTPS! It's insulting that it's obvious that these two addresses are the problem!

**Comment by hagezi** [comment]
Blocking `mparticle.map.fastly.net` CNAME for `mparticle.weather.com` leads to the problem that the search bar cannot be accessed. But it is not blocked by AdGuard DNS.

**Comment by Alex-302** [comment]
AdGuard or AdGuard DNS does not block these domains.
