### ISSUE TITLE
Videos don’t work on CBSN (via CBS News app)

### ISSUE THREAD

**Issue by B777-200ER** [AdguardTeam/AdGuardSDNSFilter#447]
When using CBS News app on iPhone, the live news feeds of CBSN do not work, yet the embedded video replays work fine.   This occurs regardless of which DNS server I’m using (AdGuard or System) so my assumption is it’s the filter; however, I‘M unable to isolate what filter is causing the issue.   Disabling DNS filtering fixes the issue.

**Comment by Alex-302** [comment]
Please provide download link and screenshot.

**Comment by Sergey-Lyapin** [comment]
@B777-200ER 
Hello, I checked this app and found out that `||pubads.g.doubleclick.net^` causes the issue.
Unfortunately we can't unblock this domain because it is being often used for advertising.

Please add this rule to DNS protection > DNS filtering > Blocklist
@@||pubads.g.doubleclick.net^$important
