### ISSUE TITLE
vod.pl, player.pl incorrect blocking cause adblock detect

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#5]
@FadeMind commented on [Mon Oct 01 2018](https://github.com/AdguardTeam/AdguardDNS/issues/350)

Adguard DNS block **required** domains for polish sites VOD.

When AdguardDNS is Active then cannot playing any content on player.pl site for example. It's showing adblock detect.

Polish filters have enabled whitelisting for:
![20181001205933-screenshot](https://user-images.githubusercontent.com/9846948/46309552-ed444d00-c5bc-11e8-9bd9-9a9b8bc1f126.png)

Site sample: https://vod.pl/playerpl-promocja/seriale-online/pulapka-odcinki,13643/odcinek-4,S01E04,113014

@AdamWr

**Comment by AdamWr** [comment]
Related issues - https://github.com/AdguardTeam/AdguardFilters/issues/5349
https://github.com/AdguardTeam/AdguardFilters/issues/15003#issuecomment-384025482
It will be neccesary to unblock `adocean.pl`, as far as I know it's used on many websites, so I think it's not good idea.

**Comment by ameshkov** [comment]
Yeah, that's not good indeed.

The only viable option to resolve it on the user side is to add the real IP of `adocean.pl` to the hosts file.

**Comment by MarekWojtulewski** [comment]
Report is from on 1 Oct 2018 but I have similar problem with shinden.pl Anti AdBlock alert caused by ADGuard DNS. So I think it's better to write about my problem here also cuz it's similar etc
I checked ADGuard DNS via DOH and DOT and same situation all the time. I also checked only DNS without ADGuard APP on Windows and with APP ADGuard on Windows etc
when you will try to open/play an episode on https://shinden.pl/
idk maybe episode 1 of Kakegurui:
https://shinden.pl/episode/50374-kakegurui/view/159468#column-one-inner
you will get alert of Anti AdBlock when u will use DNS AdGuard "Default" - DNSCrypt.

**Comment by Alex-302** [comment]
@MarekWojtulewski Hi. Could you please check with AdGuard Home instead of AdGuard DNS? ФПР has filtering log, and you can see what was blocked and which rules were triggered.

**Comment by MarekWojtulewski** [comment]
> @MarekWojtulewski Hi. Could you please check with AdGuard Home instead of AdGuard DNS? ФПР has filtering log, and you can see what was blocked and which rules were triggered.

So via AdGuard Home 
with only "AdGuard Simplified Domain Names rules" everything is ok 
but with "AdAway rules"  "adaway.org/hosts.txt" they dd adblock
idk if AdGuard DNS uses only "AdGuard Simplified Domain Name" or not 
but here on my AdGuard Home with only "AdGuard Simplified Domain Names" everything is ok
also  funny thing is that via AdGuard DNS DNSCrypt on my iPhone everything is also ok etc

**Comment by Alex-302** [comment]
@MarekWojtulewski Hi. Sorry for the late reply. Do you still have this issue? I cannot check without paid account.
As I see, that domains are frequently used and cannot be removed from filter.
