### ISSUE TITLE
blutv.com VOD video player doesn't work with AdGuardDNS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#934]
@Sanseviearia commented on [Sun Apr 10 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/233)

Hi, 2 weeks ago blutv VOD site's video player was not loading with one of the rules of EasyPrivacy, created a ticket there and it is fixed. For the last few days it started to fail with AdGuard DNS too. Probably one of the lists updated with a rule that is preventing the player to load as well.

Here's the ticket with details on EasyPrivacy's Git.
`https://github.com/easylist/easylist/issues/11456`

This issue is happening on all devices that I set AdGuard Private DNS:
DoH: Opera, Chrome on both Mac and PC. iPhone and iPad.
DoT: AndroidTV, Android Phone.

blutv
`https://www.blutv.com/canli-yayin/kanal-d-izle`

Thanks

**Comment by Sanseviearia** [comment]
[AdGuardDNS Filter](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt) has this entry below as EasyPrivacy.

`||youbora.com^`

So, just like [EasyPrivacy devs did](https://github.com/easylist/easylist/commit/734ec0dcae07d65f60b39abad9367fe5a35fa454), an exclusion like below would fix the issue.

`@@||youbora.com/*/js/adapters/jwplayer$script`
`@@||youbora.com/*/js/adapters/theoplayer$script`

**Comment by Sanseviearia** [comment]
It seems it is not fixed. Loading player was taking so long before the fix applied too, it still is.

AdGuardDNS (DoH) ON: ~25 seconds to start the video
AdGuardDNS (DoH) OFF: Video starts instantly

**Comment by Alex-302** [comment]
@Sanseviearia Please open developer tools of browser, open Network tab and reproduce an issue. 
Enter `youbora.com` in search field and make screenshot.

**Comment by Sanseviearia** [comment]
@Alex-302 Not sure if I create a New issue as the issue is evolved from _video player not loading and prevents loading website too_ to _video starts around 25 secs late with AdGuard DNS (DoH)_. 

Here's more info:
AdGuardDNS (DoH) ON: ~25 seconds to start the video
AdGuardDNS (DoH) OFF: Site's own film and series video ads starts instantly then the real video starts (those ads can be skipped)
AdGuardDNS (DoH) OFF AdGuard Extension ON: Video starts instantly

When you try those above 3, what are your results?

**Comment by Alex-302** [comment]
I can check trailers only, and they start immediately with DNS only or DNS + extension.
Account is paid.

**Comment by Alex-302** [comment]
Please test with AdGuard non-filtered DNS.

**Comment by Sanseviearia** [comment]
**AdGuardDNS (DoH) ON:** 
~25 - 35 seconds to start the video (sometimes live stream tv channel directly starts, sometimes first blutv film/series trailers/ads starts then the live stream, sometimes video ads like Siemens starts first, then trailers then live stream) website loading is slow too.
**AdGuardDNS (non-filtered) (DoH) ON:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**AdGuardDNS (DoH) OFF:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**AdGuardDNS (DoH) OFF AdGuard Extension ON:** 
Live stream tv channel starts instantly, website loading is **fast**

**BlahDNS (DoH) ON:** 
~25 - 35 seconds to start the video (sometimes live stream tv channel directly starts, sometimes first blutv film/series trailers/ads starts then the live stream, sometimes video ads like Siemens starts first, then trailers then live stream) website loading is slow too.
**BlahDNS (DoH) OFF:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**BlahDNS (DoH) OFF AdGuard Extension ON:** 
Live stream tv channel starts **instantly**, website loading is **fast**

**Quad9 (DoH) ON:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**Quad9 (DoH) OFF:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**Quad9 (DoH) OFF AdGuard Extension ON:** 
Live stream tv channel starts **instantly**, website loading is **fast**

**Cloudflare No Malware (DoH) ON:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**Cloudflare No Malware (DoH) OFF:** 
blutv film/series trailers/ads or video ads (Siemens) starts **instantly** then the live stream tv channel starts (those ads/trailers can be skipped) website loading is **fast**
**Cloudflare No Malware (DoH) OFF AdGuard Extension ON:** 
Live stream tv channel starts **instantly**, website loading is **fast**

So, AdGuard DNS and BlahDNS must be sharing some mutual lists, probably Blah using AdGuard's. As you can see site loading time and video start time is fast when using AdGuard non-filtering list. So, default list is blocking something that delays the site load and video load. Since I can't see what is blocked at the DNS level on AdGuard, I can't tell what it is. But there is an issue with AdGuardDNS default list with blutv for sure.

Btw the link in the OP is a live tv broadcast, free, no account is needed. Please check the conditions above like I did and see if you have the same as me. You can tell if the live tv is on by looking at top left of the screen, channel logo is D (blue ball and gray D without vertical line). If you have paid account, check the conditions logged out as well.

Thanks!

@ameshkov Do you have any idea?

**Comment by Alex-302** [comment]
> Btw the link in the OP is a live tv broadcast, free, no account is needed.

It does not work on my end

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/163974387-1bedb900-9e3f-4ae4-822a-a5ec160d82e6.png)

</details>

**Comment by Sanseviearia** [comment]
> It does not work on my end

Try this one below, I forgot that without VPN their content is limited (geolocked).

`https://www.blutv.com/int/canli-yayin/euro-d-izle`

**Comment by Alex-302** [comment]
Same - works fine.
Please open dev tools(press F12), reproduce an issue and export HAR. Upload it here as ZIP.

**Comment by Sanseviearia** [comment]
What does works fine mean? Have you test and compare to Quad9 for instance? I spent half an hour to test different conditions with different DNS providers in [this](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934#issuecomment-1101931709) comment the other day. But I'm receiving more tasks to do for some reason. I'm well aware of that this is free service and you guys have no obligation to fix all issues but so does EasyList. I created a ticket in their git and they fixed the issue and I'm asked no tasks to do.

The HAR file you asked has lots of identifiable data, I'm attaching SS instead. You can see how long does it take to load the site and the video from the Time column.
Left AdGuardDNS with looooooots of waiting, Right Quad9, no waiting, instant.
[Screenshot]([img]https://i.imgur.com/tUnLHXE.png[/img])

Since I proved the issue with a SS, I'm done here. The issue is there, and it's not only for me, I'm one of the mods of a forum that I wrote a guide about how to use Private, Encrypted DNS on any device to block ads and trackers and I've decided to open a ticket here on AdGuard when we started to receive posts about this issue on BluTV with AdGuard DNS ON. You are free to fix it or leave it. But I'm not going to use nor recommend AdGuard while this issue exists. I'll check in a few days later and if the issue is still there then I'll update the guide to use Quad9 instead. Neither I nor anyone else should spend this much time when reporting an issue.

**Comment by Alex-302** [comment]
I need HAR to check how long requests loaded. 100% this issue is not caused by domains blocking.
